In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
# numpy main datatype is ndarray
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2=np.array([[1,2.0,3.3],
             [4,5,6.5]])

a3=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9]],
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim , a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [13]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# create a dataframe from a Numpy array
import pandas as pd

df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [15]:
sample_array=np.array([1,2,3])

In [16]:
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [18]:
ones=np.ones((2,3))

In [19]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [22]:
zeros=np.zeros((2,3))

In [23]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array =np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [25]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[9, 6, 0, 1, 0],
       [5, 4, 0, 7, 2],
       [0, 4, 3, 0, 0]])

In [26]:
random_array.size

15

In [27]:
random_array.shape

(3, 5)

In [28]:
random_array_2=np.random.random((5,3))
random_array_2

array([[0.62970621, 0.66036279, 0.2597192 ],
       [0.02610142, 0.24300017, 0.13338662],
       [0.39003066, 0.2515051 , 0.25872449],
       [0.05602691, 0.47858027, 0.18472512],
       [0.10861078, 0.04904568, 0.28358943]])

In [29]:
random_array_2.shape

(5, 3)

In [30]:
random_array_3=np.random.rand(5,3)
random_array_3

array([[0.18593846, 0.16755698, 0.17893997],
       [0.05547588, 0.09358462, 0.66391492],
       [0.13891581, 0.12219611, 0.11214724],
       [0.50999965, 0.61493994, 0.89416578],
       [0.24377967, 0.81296971, 0.48224267]])

In [31]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4=np.random.randint(10,size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [32]:
random_array_4.shape

(5, 3)

## 3. Viewing arrays and matirces

In [33]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a1

array([1, 2, 3])

In [35]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [36]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [37]:
a1[0]

1

In [39]:
a2.shape

(2, 3)

In [38]:
a2[0]

array([1. , 2. , 3.3])

In [40]:
a3.shape

(2, 3, 3)

In [41]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [43]:
a2[1]

array([4. , 5. , 6.5])

In [44]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [47]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[8, 8, 2, 3, 2],
         [0, 8, 8, 3, 8],
         [2, 8, 4, 3, 0],
         [4, 3, 6, 9, 8]],

        [[0, 8, 5, 9, 0],
         [9, 6, 5, 3, 1],
         [8, 0, 4, 9, 6],
         [5, 7, 8, 8, 9]],

        [[2, 8, 6, 6, 9],
         [1, 6, 8, 8, 3],
         [2, 3, 6, 3, 6],
         [5, 7, 0, 8, 4]]],


       [[[6, 5, 8, 2, 3],
         [9, 7, 5, 3, 4],
         [5, 3, 3, 7, 9],
         [9, 9, 7, 3, 2]],

        [[3, 9, 7, 7, 5],
         [1, 2, 2, 8, 1],
         [5, 8, 4, 0, 2],
         [5, 5, 0, 8, 1]],

        [[1, 0, 3, 8, 8],
         [4, 4, 0, 9, 3],
         [7, 3, 2, 1, 1],
         [2, 1, 4, 2, 5]]]])

In [48]:
a4.shape ,a4.ndim

((2, 3, 4, 5), 4)

In [49]:
# Get the first 4 numbers of the inner most arrays
a4[:,:,:,:4]

array([[[[8, 8, 2, 3],
         [0, 8, 8, 3],
         [2, 8, 4, 3],
         [4, 3, 6, 9]],

        [[0, 8, 5, 9],
         [9, 6, 5, 3],
         [8, 0, 4, 9],
         [5, 7, 8, 8]],

        [[2, 8, 6, 6],
         [1, 6, 8, 8],
         [2, 3, 6, 3],
         [5, 7, 0, 8]]],


       [[[6, 5, 8, 2],
         [9, 7, 5, 3],
         [5, 3, 3, 7],
         [9, 9, 7, 3]],

        [[3, 9, 7, 7],
         [1, 2, 2, 8],
         [5, 8, 4, 0],
         [5, 5, 0, 8]],

        [[1, 0, 3, 8],
         [4, 4, 0, 9],
         [7, 3, 2, 1],
         [2, 1, 4, 2]]]])

## 4. Manipulating and comparing arrays

### Arithmetic

In [51]:
a1

array([1, 2, 3])

In [53]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [54]:
a1+ones

array([2., 3., 4.])

In [55]:
a1-ones

array([0., 1., 2.])

In [56]:
a1 *ones

array([1., 2., 3.])

In [57]:
 a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [59]:
a1/ones

array([1., 2., 3.])

In [64]:
a2/a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [61]:
# Floor division removes the decimals (round down)
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [62]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [65]:
#power of 2
a2**2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [66]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [67]:
np.add(a1,ones)

array([2., 3., 4.])

In [68]:
a1 /2

array([0.5, 1. , 1.5])

In [69]:
a1%2

array([1, 0, 1], dtype=int32)

In [70]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [71]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

performing the same operation on a number of things

In [72]:
listy_list=[1,2,3]
type(listy_list)

list

In [73]:
sum(listy_list)

6

In [75]:
type(a1)

numpy.ndarray

In [76]:
sum(a1)

6

In [77]:
np.sum(a1)

6

Use python methods ('sum()') on python datatypes and use numpy methods on numpy arrays ('np.sum()')

In [82]:
# Creative a massive Numpy array
massive_array=np.random.random(100000)
massive_array.size

100000

In [86]:
massive_array[:10]

array([0.21874937, 0.56957353, 0.45210904, 0.97023668, 0.68054469,
       0.08529557, 0.05641833, 0.4878377 , 0.88100456, 0.97640439])

In [87]:
%timeit sum(massive_array)  # pythons sum()
%timeit np.sum(massive_array)  # numpy sum()

17 ms ± 947 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
69.7 µs ± 8.12 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [88]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [89]:
np.mean(a2)

3.6333333333333333

In [90]:
np.max(a2)

6.5

In [91]:
np.min(a1)

1

In [95]:
# Standard Deviation= a measure of how spread out a group of numbers is from the mean
np.std(a2)

1.8226964152656422

In [96]:
# variance= measure of the average degree to which each number is diferent to the mean
# higher variance= wider range of numbers
# lower varinace= lower range of numbers
np.var(a2)

3.3222222222222224

In [97]:
# standard deviation= square root of variance
np.sqrt(np.var(a2))

1.8226964152656422