In [1]:
import numpy as np

## DataTypes and Attributes

In [4]:
# numpy main datatype is ndarray
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [8]:
a2=np.array([[1,2.0,3.3],
             [4,5,6.5]])

a3=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9]],
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])

In [9]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a1.shape

(3,)

In [12]:
a2.shape

(2, 3)

In [13]:
a3.shape

(2, 3, 3)

In [14]:
a1.ndim , a2.ndim, a3.ndim

(1, 2, 3)

In [15]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [16]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [17]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [18]:
# create a dataframe from a Numpy array
import pandas as pd

df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5