In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
# numpy main datatype is ndarray
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2=np.array([[1,2.0,3.3],
             [4,5,6.5]])

a3=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9]],
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim , a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [13]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# create a dataframe from a Numpy array
import pandas as pd

df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [15]:
sample_array=np.array([1,2,3])

In [16]:
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [18]:
ones=np.ones((2,3))

In [19]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [23]:
zeros=np.zeros((2,3))

In [24]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
range_array =np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [28]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[4, 2, 2, 2, 1],
       [1, 3, 4, 9, 0],
       [6, 8, 8, 8, 0]])

In [29]:
random_array.size

15

In [30]:
random_array.shape

(3, 5)

In [32]:
random_array_2=np.random.random((5,3))
random_array_2

array([[0.08136707, 0.00456455, 0.72419832],
       [0.64436471, 0.22001555, 0.07370336],
       [0.39986479, 0.83042829, 0.01155437],
       [0.48327514, 0.07268888, 0.75733996],
       [0.198966  , 0.67888179, 0.91242113]])

In [33]:
random_array_2.shape

(5, 3)

In [37]:
random_array_3=np.random.rand(5,3)
random_array_3

array([[0.17305479, 0.53802879, 0.72450668],
       [0.40568011, 0.75607886, 0.02433436],
       [0.3083912 , 0.84292959, 0.9889065 ],
       [0.98180125, 0.69334357, 0.72908662],
       [0.23330606, 0.21411038, 0.06789037]])

In [51]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4=np.random.randint(10,size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [39]:
random_array_4.shape

(5, 3)